server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: 7MB  # 单个文件最大值
      max-request-size: 14MB  # 总上传文件最大和值
      enabled: true
# 操作阿里云oss需要的参数
aliyun:
  accessKeyId:        # 阿里云的accessKeyId
  secretAccessKey:    # accessKey 密码
  oss:
    endPoint:      # Endpoint:在阿里云oss控制台查看自己使用的endpoint
    bucketName:    # bucket 名称